// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MrTS_BattleCharacterLimit","status":false,"description":"","parameters":{}},
{"name":"TitleCommandPosition","status":false,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"0","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"AltMenuScreen","status":false,"description":"メニュー画面のレイアウトを変更します。","parameters":{}},
{"name":"TitleCommandPosition","status":false,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"0","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"YEP_EventChasePlayer","status":true,"description":"v1.02 プレイヤーが特定のイベントに近づくと、イベントがプレイヤーを追いかけたりプレイヤーから逃げます","parameters":{"Sight Lock":"300","See Player":"true","Alert Timer":"120","Alert Balloon":"1","Alert Sound":"Attack1","Alert Common Event":"0","Return After":"true","Return Wait":"180"}},
{"name":"YEP_EventChasePlayer","status":false,"description":"v1.02 プレイヤーが特定のイベントに近づくと、イベントがプレイヤーを追いかけたりプレイヤーから逃げます","parameters":{"Sight Lock":"300","See Player":"true","Alert Timer":"120","Alert Balloon":"1","Alert Sound":"Attack1","Alert Common Event":"0","Return After":"true","Return Wait":"180"}},
{"name":"HorzMenuadv","status":true,"description":"ver1.03 ホリゾンタルなメニューコマンド構成","parameters":{"back":"教会","loadtext":"ロード","opacity":"255","xposi":"20","yposi":"20"}}
];
